"""大气湍流相位屏与诊断工具。

本文件服务于毕业设计“主线 B：大气湍流中 FVVB 的 OAM 谱演化”。相位屏采用
modified von Karman 谱，通过频域随机合成得到公共标量相位扰动。默认单位：
Cn2 为 m^(-2/3)，长度为 m，相位为 rad，横向角空间频率 kappa 为 rad/m。

重要假设：当前模型只用于数值趋势分析。它不包含偏振相关散射、双折射、
真实退偏振或完整实验系统误差。写入论文定量结论前，应结合最终传播距离、
光束尺寸、SLM/相机采样和湍流加载方式重新校验。"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from typing import Any

import numpy as np


@dataclass
class TurbulenceParams:
    """单层统计均匀湍流相位屏参数。"""

    cn2: float = 1e-15      # [关键变量] 折射率结构常数 C_n^2，单位 m^(-2/3)，表征湍流强度。
    dz: float = 100.0       # [关键变量] 单层相位屏厚度 / split-step 传播步长，单位 m。
    inner_scale: float = 2e-3   # [关键变量] 湍流内尺度 l0，单位 m，影响高频截止。
    outer_scale: float = 50.0   # [关键变量] 湍流外尺度 L0，单位 m，影响低频截止。
    seed: int = 1               # [关键变量] 随机种子，用于复现相位屏 realization。
    spectrum: str = "von_karman"  # 湍流谱模型；当前仅实现 modified von Karman。

    def to_dict(self) -> dict[str, Any]:
        return asdict(self)


def rytov_variance(cn2: float, wavelength: float, distance: float) -> float:
    """Return plane-wave Rytov variance ``1.23 Cn2 k^(7/6) L^(11/6)``."""
    k = 2 * np.pi / wavelength
    return float(1.23 * cn2 * k ** (7 / 6) * distance ** (11 / 6))


def fried_parameter(cn2: float, wavelength: float, distance: float) -> float:
    """Return Fried coherence diameter ``r0`` for a horizontal uniform path."""
    if cn2 <= 0 or distance <= 0:
        return float("inf")
    k = 2 * np.pi / wavelength
    return float((0.423 * k**2 * cn2 * distance) ** (-3 / 5))


def phase_psd_von_karman(
    kappa: np.ndarray,
    wavelength: float,
    cn2: float,
    dz: float,
    inner_scale: float = 2e-3,
    outer_scale: float = 50.0,
) -> np.ndarray:
    """计算 modified von Karman 单层相位屏的二维相位 PSD。

    [关键变量] kappa 是横向角空间频率，单位 rad/m；kappa0=2*pi/L0 对应外
    尺度低频截止；kappam=5.92/l0 对应内尺度高频截止。常数 0.033、5.92
    来自湍流谱模型，不应在无理论依据时随意调整。

    原英文说明：

    ``kappa`` is the transverse angular spatial frequency in rad/m.  The model
    uses ``0.033 Cn2 exp(-(kappa/kappam)^2)/(kappa^2+kappa0^2)^(11/6)`` for the
    3-D refractive-index spectrum and integrates it over the layer thickness.
    """
    k = 2 * np.pi / wavelength
    kappa0 = 2 * np.pi / outer_scale
    kappam = 5.92 / inner_scale
    # refractive_psd 是三维折射率起伏谱；再乘 2*pi*k^2*dz 得到薄相位屏 PSD。
    refractive_psd = 0.033 * cn2 * np.exp(-(kappa / kappam) ** 2) / (kappa**2 + kappa0**2) ** (11 / 6)
    return 2 * np.pi * k**2 * dz * refractive_psd


def make_phase_screen(
    n: int,
    dx: float,
    dy: float,
    wavelength: float,
    params: TurbulenceParams,
) -> np.ndarray:
    """Generate one random phase screen in radians.

    The screen is generated by spectral synthesis using the modified von Karman
    phase PSD.  The zero-frequency term is set to zero because piston phase does
    not affect intensity or OAM spectra.
    """
    if params.spectrum != "von_karman":
        raise ValueError(f"Unsupported turbulence spectrum: {params.spectrum}")

    fx = np.fft.fftfreq(n, d=dx)
    fy = np.fft.fftfreq(n, d=dy)
    FX, FY = np.meshgrid(fx, fy, indexing="xy")
    kappa = 2 * np.pi * np.hypot(FX, FY)  # [关键变量] 横向角空间频率，单位 rad/m。
    psd = phase_psd_von_karman(kappa, wavelength, params.cn2, params.dz, params.inner_scale, params.outer_scale)
    psd[0, 0] = 0.0  # 去除 piston phase；整体常相位不影响强度和 OAM 谱。

    dkx = 2 * np.pi / (n * dx)
    dky = 2 * np.pi / (n * dy)
    rng = np.random.default_rng(params.seed)
    # 频域复高斯白噪声，经 PSD 加权后反变换为实空间相位屏。
    noise = rng.normal(size=(n, n)) + 1j * rng.normal(size=(n, n))
    spectral_phase = noise * np.sqrt(psd) * np.sqrt(dkx * dky)
    # numpy ifft2 默认包含 1/(n*n)，这里乘 n*n 以沿用当前频域合成标定。
    phase = np.fft.ifft2(spectral_phase).real * n * n
    return phase - float(np.mean(phase))


def make_phase_screens(
    n: int,
    dx: float,
    dy: float,
    wavelength: float,
    params: TurbulenceParams,
    count: int,
) -> list[np.ndarray]:
    """生成 count 个统计独立的相位屏。

    每一层使用 seed + idx，保证同一组输入参数下可复现，同时不同屏之间
    不共用完全相同的随机 realization。
    """
    screens = []
    for idx in range(count):
        layer_params = TurbulenceParams(**{**params.to_dict(), "seed": params.seed + idx})
        screens.append(make_phase_screen(n, dx, dy, wavelength, layer_params))
    return screens


def phase_screen_stats(phase: np.ndarray) -> dict[str, float]:
    """Return simple statistics of a phase screen in radians."""
    phase = np.asarray(phase, dtype=float)
    return {
        "mean": float(np.mean(phase)),
        "std": float(np.std(phase)),
        "rms": float(np.sqrt(np.mean(phase**2))),
        "min": float(np.min(phase)),
        "max": float(np.max(phase)),
    }


def estimate_phase_psd_radial(
    phase: np.ndarray,
    dx: float,
    dy: float,
    nbins: int = 40,
) -> tuple[np.ndarray, np.ndarray]:
    """Estimate the radially averaged phase-screen PSD trend.

    This is a diagnostic helper for trend checks, not a substitute for a full
    turbulence-model validation.  The returned spatial frequency is angular
    transverse frequency ``kappa`` in rad/m.
    """
    phase = np.asarray(phase, dtype=float)
    ny, nx = phase.shape
    fx = np.fft.fftfreq(nx, d=dx)
    fy = np.fft.fftfreq(ny, d=dy)
    FX, FY = np.meshgrid(fx, fy, indexing="xy")
    kappa = 2 * np.pi * np.hypot(FX, FY)
    power = np.abs(np.fft.fft2(phase - np.mean(phase))) ** 2 * dx * dy / (nx * ny)

    k_flat = kappa.ravel()
    p_flat = power.ravel()
    mask = k_flat > 0
    if not np.any(mask):
        return np.array([]), np.array([])
    bins = np.linspace(float(np.min(k_flat[mask])), float(np.max(k_flat[mask])), nbins + 1)
    which = np.digitize(k_flat[mask], bins) - 1
    k_radial = []
    psd_radial = []
    for idx in range(nbins):
        use = which == idx
        if np.any(use):
            k_radial.append(float(np.mean(k_flat[mask][use])))
            psd_radial.append(float(np.mean(p_flat[mask][use])))
    return np.asarray(k_radial), np.asarray(psd_radial)


def phase_structure_function(
    phase: np.ndarray,
    dx: float,
    max_lag: int | None = None,
) -> tuple[np.ndarray, np.ndarray]:
    """Estimate a one-dimensional phase structure function along x.

    Returns lag distance in metres and ``mean((phi(x+lag)-phi(x))^2)``.  This is
    a lightweight diagnostic used to check whether the phase fluctuations grow
    with separation over the sampled range.
    """
    phase = np.asarray(phase, dtype=float)
    n = phase.shape[1]
    if max_lag is None:
        max_lag = max(1, n // 4)
    max_lag = int(min(max_lag, n - 1))
    lags = np.arange(1, max_lag + 1)
    values = []
    for lag in lags:
        diff = phase[:, lag:] - phase[:, :-lag]
        values.append(float(np.mean(diff**2)))
    return lags * dx, np.asarray(values)
